### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'n.skipReason.trim')

### ISSUE THREAD

**Issue by josephj** [efcsydney/efcsydney-roster#143]
https://sentry.io/efcsydney-10/efcsydney-roster/issues/467915416/

```
TypeError: undefined is not an object (evaluating 'n.skipReason.trim')
  at apply (modules/index/redux.js:44:49)
  at apply (../node_modules/redux-actions/es/createAction.js:24:1)
  at onSave (../node_modules/redux/es/bindActionCreators.js:3:1)
  at apply (modules/index/components/EditDay.js:70:15)
  at Ja (../node_modules/react-dom/cjs/react-dom.production.min.js:26:372)
...
(14 additional frame(s) were not displayed)
```

**Comment by josephj** [comment]
Fixed by @trust2065
